### ISSUE TITLE
Evaluate whether Network Load is a limiting performance factor

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cineast#139]
Based on a discussion with @Spiess, if someone has time they could investigate if network load is a limiting performance factor and if that is the case, how we might make it configurable for retrieval that less is requested from the storage layer, serialized and sent to the frontend (e.g. not all fields from segment / objectdescriptors might be needed). This is especially relevant since cottontail is a colum store, so having less fields in the projection could be more efficient for retrieval.

**Comment by lucaro** [comment]
I don't quite understand what you mean by 'network load', could you elaborate what load you are talking about, what generates it and which components of the stack would be affected?

**Comment by silvanheller** [comment]
Specifically, the time it takes to send all results, segment & object information and metadata from cottontail to cineast and from cineast to vitrivr-ng. I'm not convinced it's that big of an issue but @Spiess brought it up and I thought I'd document it somewhere. In the LSC context, we've had problems in the past that sending the metadata alone took 5-10 seconds for a query. @sauterl fixed this by reducing the amount of metadata imported in general, but that is not a long-term solution.

**Comment by lucaro** [comment]
In this case, the network itself is almost certainly not the limiting factor. This is especially so when the whole stack is deployed on the same physical machine, since the internal loop-back adapter does not really limit throughput. It might however be the case, that the en- and de-coding steps in both the server- and client-side API logic could be optimized, in case that should turn out to be an issue.

**Comment by silvanheller** [comment]
Closing since this is more of a benchmarking / general optimization thing
