### ISSUE TITLE
Serving and storing files from subfolders

### ISSUE THREAD

**Issue by cribin** [vitrivr/cineast#147]
Dear devs,

For my application I allow the user to upload content(images or videos) and each upload is stored in a separate subfolder.
So let's assume I have base folder _content_ and each upload generates a new subfolder _content/upload1, content/upload2, etc._. For this scenario, I have the following  questions:

- Is it possible for cineast to serve all images from the _content_ folder? If yes, which files should I modify to do so?
- Is there an issue with cottontail, if I have the same filename in different subfolders?
- How should I store the generated thumbnails for each content? 
- After the first extraction, for each subsequent extraction, I can simply call the _extract --extraction job.json_ command with the appropriate input and thumbnail output path in the job file correct?

Best,

Ribin

**Comment by lucaro** [comment]
> Is it possible for cineast to serve all images from the content folder? If yes, which files should I modify to do so?

Yes it is and you don't even have to modify anything. Cineast stores the path of the media object relative to the location from where you started the extraction, so as long as you keep the paths consistent, you can have as many sub-directories as you want.

> Is there an issue with cottontail, if I have the same filename in different subfolders?

No, it simply stores the path. As long as all paths are unique, there is no issue. You can even use the same file name as often as you want, as long as these files are not in the same directory.

> How should I store the generated thumbnails for each content?

The same way you would otherwise: using the thumbnail exporter. Since the naming of the generated thumbnails is based on the id of the media object, there should be no problem in terms of collision (unless you have duplicate ids, but then you have larger problems).

> After the first extraction, for each subsequent extraction, I can simply call the extract --extraction job.json command with the appropriate input and thumbnail output path in the job file correct?

You would probably want to modify the path in job file in order to avoid having to scan all the items which were already extracted again. Cineast does also have an API to run the extraction, see https://github.com/vitrivr/cineast/blob/master/cineast-api/src/main/java/org/vitrivr/cineast/api/rest/handlers/actions/session/ExtractItemHandler.java

**Comment by cribin** [comment]
Let's say I have my base folder _content_ containing two subfolders _content/upload1_ and _content/upload2_, which are already extracted to the database. Now I add a third folder _content/upload3_ which I want to extract. In order for the correct path to be used, I have to specify _content_ as the input path for the job file correct? But wouldn't then the data in the other two subfolders be scanned again as well? On the other hand, when I choose _content/upload3_ as the input path for extraction, the stored path would not be correct, when I serve the data from the _content_ folder. So how can I avoid that already scanned subfolders are evaluated again by the extractor?

**Comment by lucaro** [comment]
Two options come to mind: either use the extraction API (which was intended for these kinds of use cases) or change the extraction logic to store the absolute path in the database, which would enable you to build specific jobs for each of your new directories.

**Comment by cribin** [comment]
The extraction API looks promising. Is there an example and documentation on how to use it?

**Comment by lucaro** [comment]
Yes, what I linked above is part of the REST API. I don't think we have any external documentation on it, but if you have a look at the code it should be reasonably straight forward to understand. Also, there's an other project which had a similar use case to yours which used it successfully in the past, see https://github.com/sauterl/demeter.

**Comment by cribin** [comment]
When I considered the other option you mentioned of storing the absolute path in the database, I encountered the following problem: 
- After the first extraction with four images I have the ids i_0000001, i_0000002, etc. in the database
- After the second extraction with four other images, the generated ids are again  i_0000001, i_0000002,... etc.

Is this normal behaviour, since I get a collision in the database and the generated thumbnails are being overwritten by subsequent extractions?

Best,

Ribin

**Comment by lucaro** [comment]
The way object ids are generated is configurable, see https://github.com/vitrivr/cineast/tree/master/cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/idgenerator for an overview of the available options.

**Comment by cribin** [comment]
Thanks, by generating unique ids and storing the absolute path I was able to resolve the issue.
