### ISSUE TITLE
About database storage

### ISSUE THREAD

**Issue by zh57398** [vitrivr/cineast#148]
Can I use adampro instead of cotton ILDB for database storage? Is there a specific description of how adampro connects to cineast? Thank you very much.

**Comment by lucaro** [comment]
Sure, although there are currently not all that many benefits of using ADAMpro over Cottontail, unless you have a very large dataset and you want to setup ADAMpro as a distributed system across multiple machines. Cineast connects to ADAMpro (not the other way around) in the same way as it connects to Cottontail, you simply need to specify the database type as well as the host and port in the cineast config.

**Comment by silvanheller** [comment]
Yes, you can simply replace `COTTONTAIL` with `ADAMPRO` in the config files. See e.g. https://github.com/vitrivr/cineast/blob/0246e62723520f2c55f15ca6b5458646685a834b/cineast-core/src/main/java/org/vitrivr/cineast/core/config/DatabaseConfig.java#L54

However, ADAMpro support (and ADAMpro itself) is not maintained anymore since Cineast 2. Cottontail supports more functionality and is faster. If you encounter any issues with cottontail, let us know.
