### ISSUE TITLE
Meaning of weights in cineast.json file

### ISSUE THREAD

**Issue by cribin** [vitrivr/cineast#149]
Dear devs,

What do the weights mean for each feature in the cineast.json file? How do the weights affect the results?
Furthermore, is it possible to query for multiple features with the AND operator? So for example, query all images with a certain color and a score between 4 and 5.

Best,

Ribin

**Comment by lucaro** [comment]
The weights are used for the score fusion per category. When you have multiple feature modules, you need a way to aggregate these scores into one list. The weights enable you to change the influence of one feature's score with respect to another. The weights found in the config which are used for the low-level visual features are set empirically.

**Comment by cribin** [comment]
So how can I achieve the AND condition when querying with multiple categories? Currently in the UI, when I search for an image with a certain color and add the boolean condition for my score, the shown results are using the OR condition.

**Comment by lucaro** [comment]
The categories are evaluated independently and their scores are fused in the front end. Since these are not sets but ordered lists, it's not exactly equivalent to a Boolean 'or' since elements which are present in both lists tend to have a higher combined score than those which are only present in one. If you explicitly want to limit the results of one category to those of another one, you can use query stages. This will cause cineast to consider only the results retrieved in the first stage to be part of the second and so on. Stages are based on query modalities and are present in the UI. You can simply push your second modality to a later stage to force it to only consider results from the first.

**Comment by cribin** [comment]
Ok, so can I do this directly on the webpage or do I need to configure something in the config file of vitrivr-ng? Currently, when I add an additional query container by clicking the green plus button, they are all on stage 0.

**Comment by lucaro** [comment]
You can do this directly in the UI, there are little arrow buttons next to the stage to move the individual input types up and down.

**Comment by cribin** [comment]
I'm probably missing something, but which button are you referring to?
![Screenshot_2020-10-07 Vitrivr NextGen](https://user-images.githubusercontent.com/20424212/95352455-8dc35b00-08c2-11eb-8938-0f5d97767290.png)

**Comment by sauterl** [comment]
In this particular use case, you do not use the green + button, but instead click on the query-by-sketch button and use the 
magnifying glass icon to move the query-by-sketch to the second stage

**Comment by cribin** [comment]
Ah, now I get it. Thanks a lot! Maybe this could be made a bit more intuitive?

**Comment by lucaro** [comment]
Yes, a re-design of this entire thing is in the works, it's however in rather early stages and not a high priority activity, so there's no estimate on when it might be available yet.
