### ISSUE TITLE
Access served location of an image, given the shotID

### ISSUE THREAD

**Issue by cribin** [vitrivr/cineast#150]
I have the following scenario: Given a _SegmentContainer_ object, I want to access its absolute path and the served location/url(as specified in the cineast.json file) of the image via code. Is this possible? If no, what would be the best approach to implement such functionality in cineast?

Best,

Ribin

**Comment by cribin** [comment]
Is there already code supporting this functionality or do I need to implement something myself. If it is the latter, which class stores the information about the cineast serve-location of content?

**Comment by lucaro** [comment]
I don't quite understand the question, where would you want to access this information from?

**Comment by cribin** [comment]
Ideally, I want to access it from my custom Extractor class. I need to send the Url of the current image/video via Rest to a python server and receive feedback.

**Comment by lucaro** [comment]
At the time of the extraction, there is no URL, at least not from cineasts point of view, since the object has not been extracted and hence does not need to be served. You appear to intend to use the whole pipeline very differently from what it was designed to to. The job of the extraction runtime is to abstract all this information away, so that the extractors only need to care about the actual multimedia content of a document and not where it came from. If you really want to do it this way, have a look at the `MetadataExtractor`, which is capable of accessing a media file directly.

**Comment by cribin** [comment]
In that case, what would be a better way to achieve what I want to do, by using the pipeline as it was designed?

**Comment by lucaro** [comment]
Using the actual content of the media object which the extraction runtime provides to the extractors.
