### ISSUE TITLE
Handling of Videos in cineast

### ISSUE THREAD

**Issue by RibinMTC** [vitrivr/cineast#154]
Dear devs,

How does an extractor handle videos in cineast? Can I access individual frames? Can I access a segment of the video given a start and end time?
Which video formats are supported?

Best,

Ribin

**Comment by lucaro** [comment]
An extractor has to implement the corresponding interface (see https://github.com/vitrivr/cineast/blob/master/cineast-core/src/main/java/org/vitrivr/cineast/core/features/extractor/Extractor.java) which defines a method
`void processSegment(SegmentContainer container)`. A `SegmentContainer` contains all relevant information about a media segment. In case of a video, it has information about the start and end times of the segment with respect to the videos, all video frames within the segment, the audio samples and subtitle elements if available as well as some aggregated representations, such as a pixel-wise average over all frames, which are computed on demand.

**Comment by RibinMTC** [comment]
And how are the segmentations of a video determined? Can I set the time frames of the segments via code?

**Comment by lucaro** [comment]
Segmenters are configurable, see https://github.com/vitrivr/cineast/tree/master/cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/segmenter. Again, the segment knows its start and end time.

**Comment by RibinMTC** [comment]
I want to process a video entirely, without segmenting it. How would I do that? I have seen that a _PassthroughSegmenter_ exists, but it is not clear to me, how to use it for a video. Could you provide me with an example?

**Comment by lucaro** [comment]
That one is not really designed to be used for videos. Since cineast assumes that it will always have access to all frames of a segment, having an entire video as one segment is not usually a use case. How long are the videos you want to process?

**Comment by RibinMTC** [comment]
The length of video is not yet fixed, but it could from seconds to couple of minutes.

**Comment by lucaro** [comment]
Cineast is designed as a retrieval engine and in so far, it makes sense to segment temporal media documents such as videos reasonably closely along the time dimension, in order to have high enough resolution for retrieved results to be useful. You can change this, but it might have unintended consequences in terms of memory usage. There is currently no segmenter which you could force to not segment a video in any case, so you'll have to implement one. It should be reasonably straight forward, you can have a look at the others in https://github.com/vitrivr/cineast/tree/master/cineast-core/src/main/java/org/vitrivr/cineast/core/extraction/segmenter/video to see how they work in general.
