### ISSUE TITLE
Switch CI on dev & master to Dockerhub

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cineast#195]
Since Cottontail has migrated to Dockerhub, the CI needs to be updated accordingly.

`dev` should use 0.12.+, ~`master` should use 0.10.+~ we should wait with master migration before problems are fixed on dev

**Comment by Spiess** [comment]
While the CI configuration was successfully migrated to DockerHub for the Cottontail DB image, the cineast-core:test task is aborted due to timeout.
From the debug output it seems to be stuck at the Cottontail integration tests. Something may still be incorrectly configured for the Cottontail DB Docker image.

**Comment by silvanheller** [comment]
It seems to me that this is a networking issue. The Actions job hangs in the following loop:

```
2021-04-06T08:12:05.787+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2021-04-06T08:12:05.787+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
```

for which i have not found any sensible information with quite some googling. I think the issue is probably that somehow while connecting Cineast to the Docker Container, the job hangs. I've introduced a timeout of 5 minutes to prevent the 6 hour actions job, but i haven't found a good solution.

**Comment by silvanheller** [comment]
I was able to resolve the CI Issues by bumping the cottontail docker container version
