### ISSUE TITLE
Thumbnails for segments of objects with underscores in the filename are not properly resolved when being served

### ISSUE THREAD

**Issue by simonpeterhans** [vitrivr/cineast#210]
It's currently impossible to serve thumbnails for segments of objects with underscores in the filename.  

This is probably due to `org.vitrivr.cineast.api.rest.resolvers.FileSystemThumbnailResolver` splitting by `_` and using the first two parts to determine the folder, thus cutting off part of the ID if it contains an underscore.

**Comment by lucaro** [comment]
This is not really a bug, since the way IDs are currently handled, the underscore is a special character with a defined semantic. Analogously, you wouldn't consider it a bug not being able to use a `/` in your filename either. It is however worth discussing if we should encode anything into the IDs in the first place or just replace everything with UUIDs and have cineast do all the resolving.

What did you even do to have underlines in the ID?

**Comment by silvanheller** [comment]
If a file has an `_` in the name, the generated segment id will contain more than two `_` if you generate ids based on filename. I think this is an easy fix for Thumbnail Serving, we can simply look for the folder based on everything before the last `_`

**Comment by lucaro** [comment]
Sure, or just use one of the many other mechanisms to generate ids other than the filename.

**Comment by silvanheller** [comment]
Fixed on `dev`, will be merged to `master` with #207
