### ISSUE TITLE
Exception in SolrTextRetriever

### ISSUE THREAD

**Issue by gloriaaaa** [vitrivr/cineast#95]
Sorry to disturb you ,but could you please tell me is the scene caption function described in the paper "Deep Learning-Based Concept Detection in vitrivr" available now?
Encountered such an error while using cineast's DescriptionTextSearch feature extraction module:

`2019-11-21 16:05:42.695 [pool-5-thread-1] FATAL o.v.c.c.r.ExtractionTask - EXTRACTION ERROR in DescriptionTextSearch: for segmentID i_50ANYl8J0vkx7627_000001 
java.lang.UnsupportedOperationException: Not supported by default
	at org.vitrivr.cineast.core.features.abstracts.SolrTextRetriever.processSegment(SolrTextRetriever.java:74)
	at org.vitrivr.cineast.core.runtime.ExtractionTask.run(ExtractionTask.java:28)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

In the processSegment function of SolrTextRetriever.java, I found that this exception was thrown by default. Is there a problem with my usage?

**Comment by lucaro** [comment]
The generation of these captions had to be produced by an external application and not by cineast itself, since the whole approach was rather experimental at the time. As described in the paper, we used the method implemented in https://github.com/tensorflow/models/tree/master/research/im2txt. The generation of these sentences might be directly integrated into cineast at some point, if it turns out to be sufficiently useful.

**Comment by gloriaaaa** [comment]
That‘s very helpful. Thank you so much！
